/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author lenovo212
 */
public class GUI extends javax.swing.JFrame {

    CentralMain central;

    /**
     * Creates new form GUI
     */
    public GUI(CentralMain cm) {
        this.central = cm;
        initComponents();
        initSongsList();
    }

    private void initSongsList() {
        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Moods Playlist");
        DefaultTreeModel dtm = new DefaultTreeModel(rootNode, true);
        ArrayList<String> moodsList = this.central.getMoodsList();

        for (int i = 0; i < moodsList.size(); i++) {
            DefaultMutableTreeNode moodNode = new DefaultMutableTreeNode(moodsList.get(i));
            ArrayList<Playlist.Song> songs = this.central.playlist.getSongsWithMood(moodsList.get(i));
            for (int j = 0; j < songs.size(); j++) {
                DefaultMutableTreeNode songNode = new DefaultMutableTreeNode(songs.get(j).getFile().getName(),false);
                moodNode.add(songNode);
            }
            rootNode.add(moodNode);
        }
        this.jSongsList.setModel(dtm);
        for (int i = 0; i < this.jSongsList.getRowCount(); i++) {
            this.jSongsList.expandRow(i);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPrevButton = new javax.swing.JButton();
        jNextButton = new javax.swing.JButton();
        jPlayButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSongsList = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPrevButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/icon-prev.png"))); // NOI18N

        jNextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/icon-next.png"))); // NOI18N

        jPlayButton.setBackground(new java.awt.Color(255, 255, 255));
        jPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/icon-play.png"))); // NOI18N
        jPlayButton.setFocusPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPrevButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPlayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNextButton)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPrevButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSongsList.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jSongsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jNextButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jPlayButton;
    private javax.swing.JButton jPrevButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jSongsList;
    // End of variables declaration//GEN-END:variables
}
