/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import udp.datatransmission.DataTransmission;

/**
 *
 * @author lenovo212
 */
public class GUI extends javax.swing.JFrame {

    public final static String NEXT_BUT = "0";
    public final static String START_BUT = "1";
    public final static String PREV_BUT = "2";
    public final static String VOL_UP = "3";
    public final static String VOL_DWN = "4";
    GUIController controller;
    SongListTreeModel songlistTreeModel;

    GUI(SongListTreeModel sltModel, GUIController gc) {
        this.controller = gc;
        this.songlistTreeModel = sltModel;
        initComponents();
        loadMoodsList();
        setSongTreeModel(sltModel);
    }

    protected void setSongTreeModel(SongListTreeModel model) {
        this.jSongsList.setModel(model);

        //expand all the tree
        for (int i = 0; i < this.jSongsList.getRowCount(); i++) {
            this.jSongsList.expandRow(i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPrevButton = new javax.swing.JButton();
        jNextButton = new javax.swing.JButton();
        jPlayButton = new javax.swing.JToggleButton();
        jVolUpButton = new javax.swing.JButton();
        jVolDwnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSongsList = new javax.swing.JTree();
        jRemoveButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jPathField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMoodsList = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jBrowseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsongonplayText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BioBeat Central Control");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPrevButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon-prev.png"))); // NOI18N
        jPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevButtonActionPerformed(evt);
            }
        });

        jNextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon-next.png"))); // NOI18N
        jNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextButtonActionPerformed(evt);
            }
        });

        jPlayButton.setBackground(new java.awt.Color(255, 255, 255));
        jPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon-play.png"))); // NOI18N
        jPlayButton.setFocusPainted(false);
        jPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayButtonActionPerformed(evt);
            }
        });

        jVolUpButton.setText("+ Volume");
        jVolUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolUpButtonActionPerformed(evt);
            }
        });

        jVolDwnButton.setText("- Volume");
        jVolDwnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolDwnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jPrevButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPlayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jVolUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jVolDwnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jVolUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVolDwnButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPrevButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPlayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSongsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSongsList.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jSongsList);

        jRemoveButton.setText("Remove Song");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        jAddButton.setText("Add Song");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jPathField.setText("Enter file path here");

        jLabel1.setText("Path:");

        jMoodsList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "moods list" }));

        jLabel2.setText("Song Mood:");

        jBrowseButton.setText("Browse");
        jBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("currently playing >> ");

        jsongonplayText.setText("Paused");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPathField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jBrowseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMoodsList, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsongonplayText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jsongonplayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jMoodsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRemoveButton)
                    .addComponent(jLabel2)
                    .addComponent(jBrowseButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/////////////////////////////////////////////////////////
    /////// ACTION CALLBACK METHODS TO THE CONTROLLER 
    //////////////////////////////////////////////
    private void jPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayButtonActionPerformed
        if (!jPlayButton.isSelected()) { // paused
            jPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon-play.png")));
            this.controller.sendMsg(DataTransmission.CMD_PAUSE);
        } else { //playing
            jPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon-pause.png")));
            this.controller.sendMsg(DataTransmission.CMD_PLAY);
        }
    }//GEN-LAST:event_jPlayButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        File f = new File(jPathField.getText());
        if (!f.isFile() || !f.exists()) {
            CentralMain.displayErrorDialog("The song file path specified is invalid. \nmake sure the song is still there");
            return;
        }

        CentralMain.copyFileUsingStream(f, new File(CentralMain.BASE_URL + f.getName()));
        this.controller.addSong(f.getName(), (String) jMoodsList.getSelectedItem());
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseButtonActionPerformed
        displayBrowserDialog();
    }//GEN-LAST:event_jBrowseButtonActionPerformed

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        System.out.println((String) jMoodsList.getSelectedItem());
        Object[] paths = jSongsList.getSelectionPath().getPath();
        System.out.println(paths.length);
        if (paths.length != 3) {
            return;
        }
        String mood = paths[1].toString();
        String song = paths[2].toString();
        this.controller.removeSong(song, mood);
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    private void jNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextButtonActionPerformed
        this.controller.actionPerformed(new ActionEvent(this, 0, GUI.NEXT_BUT));
    }//GEN-LAST:event_jNextButtonActionPerformed

    private void jPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevButtonActionPerformed
        this.controller.actionPerformed(new ActionEvent(this, 0, GUI.PREV_BUT));    }//GEN-LAST:event_jPrevButtonActionPerformed

    private void jVolUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolUpButtonActionPerformed
        this.controller.actionPerformed(new ActionEvent(this, 0, GUI.VOL_UP));
    }//GEN-LAST:event_jVolUpButtonActionPerformed

    private void jVolDwnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolDwnButtonActionPerformed
        this.controller.actionPerformed(new ActionEvent(this, 0, GUI.VOL_DWN));
    }//GEN-LAST:event_jVolDwnButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jBrowseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jMoodsList;
    private javax.swing.JButton jNextButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPathField;
    private javax.swing.JToggleButton jPlayButton;
    private javax.swing.JButton jPrevButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jSongsList;
    private javax.swing.JButton jVolDwnButton;
    private javax.swing.JButton jVolUpButton;
    private javax.swing.JLabel jsongonplayText;
    // End of variables declaration//GEN-END:variables

    private void loadMoodsList() {
        ArrayList<String> moods = this.songlistTreeModel.getMoods();
        jMoodsList.setModel(new DefaultComboBoxModel(moods.toArray()));
    }

    public void setPathField(String path) {
        jPathField.setText(path);
    }

    public void songonplaytext(String txt) {
        jsongonplayText.setText(txt);
    }

    public void displayBrowserDialog() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.getName().endsWith(".mp3") || f.isDirectory()) {
                    return true;
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "mp3";
            }
        });
        int option = jFileChooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            setPathField(jFileChooser.getSelectedFile().getPath());
        }
    }
}
